#!/usr/bin/env bash

if [ "$1" = "--introduce" ]; then
    echo "$0 는 로컬에 설치된 johngrib.github.io 디렉토리에서 CLI 명령과 관련된 문서를 검색해 미리보기를 제공해 줍니다."
    exit 0
fi

wiki=`stat -f "%N" ~/johngrib.github.io/_wiki`

if [ "$wiki" = "" ]; then
    echo "invalid wiki location."
    return 0
fi

name=`find $wiki/cmd -name '*.md' 2> /dev/null \
    | xargs egrep 'summary|title' \
    | awk -F':' 'NR%2==1 { name=$1; title=$3 } NR%2==0 { print name, ":", title, ":", $3 }' \
    | sed "s,"$wiki"/,," \
    | column -ts':' \
    | sort \
    | fzf --preview "showPreview $wiki/{1}" --query="$1" \
    | cut -d' ' -f1 \
`

if [ "$name" = "" ]; then
    exit
fi

showPreview $wiki/$name | less -R -X

