-- NOTE: This plugin is currently not working as expected with lazy.nvim.
-- It has been temporarily disabled and will be revisited later.
-- (이 플러그인은 현재 lazy.nvim에서 예상대로 작동하지 않습니다.
-- 일시적으로 비활성화되었으며 나중에 다시 시도할 예정입니다.)

-- return {
--   'gelguy/wilder.nvim',
--   config = function()
--     local wilder = require('wilder')
-- 
--     wilder.setup({
--       modes = {':', '/', '?'},
--       next_key = '<c-n>',
--       previous_key = '<c-p>',
--       accept_key = '<Down>',
--       reject_key = '<Up>',
--     })
-- 
--     local pmenu_hl = wilder.make_hl(nil, 'Pmenu', {}, '#e4e4e4', '#4e4e4e')
--     local pmenusel_hl = wilder.make_hl(nil, 'PmenuSel', {}, '#00ff00', '#585858')
--     local selected_hl = wilder.make_hl(nil, nil, { bold = true }, '#00ff00', '#585858')
-- 
--     wilder.set_option('renderer', wilder.popupmenu_renderer(wilder.popupmenu_border_theme({
--       highlights = {
--         border = 'Normal',
--         Pmenu = pmenu_hl,
--         PmenuSel = pmenusel_hl,
--         selected = selected_hl,
--       },
--     })))
--   end,
-- }
return {}